# Generated by Django 4.2.1 on 2023-05-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile/user-profile.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
